name: Update CSV File

on:
  schedule:
    - cron: '*/1 * * * *'  # Executa a cada 1 minuto

jobs:
  update-csv:
    runs-on: windows-latest  # Executa no ambiente Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Check if CSV file has changed
        id: check_changes
        run: |
          cd C:\Users\Administrador\Desktop\PAINELCSV
          git diff --quiet || echo "Files have changed"
          echo "::set-output name=changed::$(if [ $? == 0 ]; then echo 'false'; else echo 'true'; fi)"
          
      - name: Copy CSV to GitHub repository
        if: steps.check_changes.outputs.changed == 'true'
        run: |
          cd C:\Users\Administrador\Desktop\PAINELCSV
          copy painel.CSV %GITHUB_WORKSPACE%\painel.CSV
          cd %GITHUB_WORKSPACE%
          git config --global user.email "cocjoanin001@gmail.com"
          git config --global user.name "cdjoanin"
          git add .
          git commit -m "Atualizando arquivo CSV automaticamente"
          git push origin main
