name: Validate CSV Update

on:
  push:
    branches:
      - main  # Altere para o nome da sua branch principal, se diferente

jobs:
  validate-csv:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate CSV presence
        run: |
          if (Test-Path -Path painel.CSV) {
            Write-Output "painel.CSV encontrado."
          }
          else {
            Write-Error "painel.CSV não encontrado!"
            exit 1
          }
        shell: pwsh
