name: Update CSV File

on:
  schedule:
    - cron: '*/1 * * * *' # Executa a cada 1 minuto

jobs:
  update-csv:
    runs-on: windows-latest # Define que o ambiente é Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update CSV
        shell: pwsh # Usa o PowerShell para executar os comandos
        run: |
          Copy-Item -Path "C:\Users\Administrador\Desktop\PAINELCSV\painel.CSV" -Destination $env:GITHUB_WORKSPACE\painel.CSV -Force
          Set-Location -Path $env:GITHUB_WORKSPACE
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@users.noreply.github.com'
          git add .\painel.CSV
          git commit -m "Atualizando arquivo CSV automaticamente"
          git push origin main
